---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "s3s3mirror.fullname" . }}
  labels:
    app: {{ template "s3s3mirror.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  sourceSecretKey: "{{ .Values.s3s3mirror.source.secretKey | b64enc }}"
{{- if .Values.s3s3mirror.source.encryption }}
  sourceEncryptionKey: "{{ .Values.s3s3mirror.source.encryptionKey | b64enc }}"
{{- end }}
  destinationSecretKey: "{{ .Values.s3s3mirror.destination.secretKey | b64enc }}"
{{- if .Values.s3s3mirror.destination.encryption }}
  destinationEncryptionKey: "{{ .Values.s3s3mirror.destination.encryptionKey | b64enc }}"
{{- end }}
